const express = require('express');
const cors = require('cors');
const { randomUUID } = require('crypto');

const app = express();

app.use(cors());
app.use(express.json());

/**
 * In-memory store.
 * Each project includes autogenerated phases.
 */
const store = {
  projects: [],
  plans: new Map(),
  inceptionArtifacts: new Map(),
  iterations: new Map(),
  roles: new Map(),
};

const resetStore = () => {
  store.projects.length = 0;
  store.plans.clear();
  store.inceptionArtifacts.clear();
  store.iterations.clear();
  store.roles.clear();
};

const PHASE_TEMPLATES = [
  { key: 'inception', name: 'Incepción' },
  { key: 'elaboration', name: 'Elaboración' },
  { key: 'construction', name: 'Construcción' },
  { key: 'transition', name: 'Transición' },
];

const newId = () => randomUUID();

const validateRequired = (fields, body) => {
  const missing = fields.filter((f) => !body[f]);
  return missing.length ? `Faltan campos: ${missing.join(', ')}` : null;
};

const validateDateRange = (start, end) => {
  if (!start || !end) return null;
  return new Date(start) <= new Date(end) ? null : 'La fecha de inicio debe ser anterior o igual a la fecha fin';
};

const createProjectPhases = (projectId) =>
  PHASE_TEMPLATES.map((phase, idx) => ({
    id: newId(),
    key: phase.key,
    name: phase.name,
    order: idx + 1,
    projectId,
    status:
      idx === 0
        ? 'in-progress'
        : idx === 1
        ? 'not-started'
        : 'not-started',
  }));

app.get('/', (_req, res) => {
  res.json({ status: 'ok', version: 'v1' });
});

app.post('/projects', (req, res) => {
  const error = validateRequired(['name'], req.body);
  if (error) return res.status(400).json({ error });

  const { name, description = '', startDate = null, endDate = null } = req.body;
  const rangeError = validateDateRange(startDate, endDate);
  if (rangeError) return res.status(400).json({ error: rangeError });

  const id = newId();
  const phases = createProjectPhases(id);
  const now = new Date().toISOString();
  const project = {
    id,
    name,
    description,
    startDate,
    endDate,
    phases,
    status: 'active',
    createdAt: now,
    updatedAt: now,
  };
  store.projects.push(project);
  res.status(201).json(project);
});

app.get('/projects', (_req, res) => {
  res.json(store.projects);
});

app.get('/projects/:id', (req, res) => {
  const project = store.projects.find((p) => p.id === req.params.id);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  res.json(project);
});

const findProject = (id) => store.projects.find((p) => p.id === id);

app.get('/projects/:id/plan', (req, res) => {
  const project = findProject(req.params.id);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  res.json(store.plans.get(project.id) || null);
});

app.post('/projects/:id/plan', (req, res) => {
  const project = findProject(req.params.id);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  const error = validateRequired(['summary'], req.body);
  if (error) return res.status(400).json({ error });

  const now = new Date().toISOString();
  const plan = {
    id: newId(),
    projectId: project.id,
    createdAt: now,
    updatedAt: now,
    ...req.body,
  };
  store.plans.set(project.id, plan);
  res.status(201).json(plan);
});

app.put('/projects/:id/plan', (req, res) => {
  const project = findProject(req.params.id);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  const existing = store.plans.get(project.id);
  if (!existing) return res.status(404).json({ error: 'Plan no encontrado' });
  const plan = {
    ...existing,
    ...req.body,
    updatedAt: new Date().toISOString(),
  };
  store.plans.set(project.id, plan);
  res.json(plan);
});

const findPhase = (project, phaseId) => project.phases.find((f) => f.id === phaseId);

app.get('/projects/:projectId/phases/:phaseId/iterations', (req, res) => {
  const project = findProject(req.params.projectId);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  const phase = findPhase(project, req.params.phaseId);
  if (!phase) return res.status(404).json({ error: 'Fase no encontrada' });
  res.json(store.iterations.get(phase.id) || []);
});

app.post('/projects/:projectId/phases/:phaseId/iterations', (req, res) => {
  const project = findProject(req.params.projectId);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  const phase = findPhase(project, req.params.phaseId);
  if (!phase) return res.status(404).json({ error: 'Fase no encontrada' });

  const error = validateRequired(['name', 'startDate', 'endDate'], req.body);
  if (error) return res.status(400).json({ error });
  const rangeError = validateDateRange(req.body.startDate, req.body.endDate);
  if (rangeError) return res.status(400).json({ error: rangeError });

  const iteration = {
    id: newId(),
    phaseId: phase.id,
    projectId: project.id,
    name: req.body.name,
    startDate: req.body.startDate,
    endDate: req.body.endDate,
    goal: req.body.goal || '',
  };
  const list = store.iterations.get(phase.id) || [];
  list.push(iteration);
  store.iterations.set(phase.id, list);
  res.status(201).json(iteration);
});

app.get('/projects/:id/inception-artifacts', (req, res) => {
  const project = findProject(req.params.id);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  res.json(store.inceptionArtifacts.get(project.id) || []);
});

app.post('/projects/:id/inception-artifacts', (req, res) => {
  const project = findProject(req.params.id);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  const error = validateRequired(['name', 'status'], req.body);
  if (error) return res.status(400).json({ error });

  const artifact = {
    id: newId(),
    projectId: project.id,
    name: req.body.name,
    status: req.body.status,
    required: Boolean(req.body.required),
  };
  const list = store.inceptionArtifacts.get(project.id) || [];
  list.push(artifact);
  store.inceptionArtifacts.set(project.id, list);
  res.status(201).json(artifact);
});

app.get('/projects/:id/roles', (req, res) => {
  const project = findProject(req.params.id);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  res.json(store.roles.get(project.id) || []);
});

app.post('/projects/:id/roles', (req, res) => {
  const project = findProject(req.params.id);
  if (!project) return res.status(404).json({ error: 'Proyecto no encontrado' });
  const error = validateRequired(['user', 'role'], req.body);
  if (error) return res.status(400).json({ error });

  const assignment = {
    id: newId(),
    projectId: project.id,
    user: req.body.user,
    role: req.body.role,
    assignedAt: new Date().toISOString(),
  };
  const list = store.roles.get(project.id) || [];
  list.push(assignment);
  store.roles.set(project.id, list);
  res.status(201).json(assignment);
});

app.post('/admin/reset', (_req, res) => {
  resetStore();
  res.status(204).end();
});

module.exports = {
  app,
  store,
  resetStore,
};
